---
- name: create user
  user:
    name: admin
    comment: admin
    uid: 1050
    shell: /bin/bash
    home: /home/admin/
    password: "{{ admin_password }}"
    groups: sudo
    append: yes
    state: present

- name: set authorized keys
  authorized_key:
    user: admin
    key: " {{ item }} "
    state: present
    exclusive: true
  with_items:
    - "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIM2MtpCKuFZeSZCNZay4zYIL01+e6HX72FCpQCQMHxYk ouailderghal1@gmail.com"
