---
- hosts: lab4
  user: debian
  become: yes

  pre_tasks: 
    - name: Set hostname
      tags: hostname
      hostname: name="{{ hostname }}"

    - name: DATE AND TIME CONFIGURATION
      tags: datetime
      block:
        - name: Set timezone to Africa/Algiers
          tags: timezone
          timezone: name=Africa/Algiers

        - name: Install NTP
          tags: ntp
          apt: name=ntp state=present

        - name: Enable and run NTP service
          tags: ntp
          service: name=ntp state=started enabled=yes

    - name: SYSTEM UPDATE AND UPGRADE
      tags: update,upgrade
      block:
        - name: Copy sources.list file
          tags: sources.list
          copy:
            src: ./config/apt/sources.list
            dest: /etc/apt/sources.list
            owner: root
            group: root
            backup: yes

    - name: Copy bash configuration
      tags: bash,bashrc
      copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        owner: root
        group: root
        backup: yes
      with_items:
        - { src: ./config/bash/skel.bash, dest: /etc/skel/.bashrc }
        - { src: ./config/bash/skel.bash, dest: /etc/bash.bashrc }

    - name: Update cache and full system upgrade
      tags: update,upgrade,cache_update
      apt:
        update_cache: yes
        upgrade: dist
        cache_valid_time: 3600
        force_apt_get: yes

  tasks:
    - name: USER CREATION (ADMINISTRATOR, GUEST)
      tags: users
      block:
        - name: Copy BASH configuration file
          tags: bash,bashrc
          copy:
            src: "{{ item.src }}"
            dest: "{{ item.dest }}"
            owner: root
            group: root
            backup: yes
          with_items:
            - { src: ./config/bash/skel.bash, dest: /etc/skel/.bashrc }
            - { src: ./config/bash/skel.bash, dest: /etc/bash.bashrc }

        - name: Create guest user
          tags: guest_user
          user:
            name: guest
            comment: guest
            uid: 1040
            shell: /bin/bash
            home: /home/guest/
            password: "$6$f.3g1cc1i/7KZNfc$T0.svXQuiNVwEA91XzINK1MjVtOy80/aJTCcgPNoSVqTDxZGm1559uGS5i.H1xPPcrU4KldAbQjXyseqtMqsx1"
            skeleton: no
            state: present

        - name: Create admin user
          tags: admin
          user:
            name: admin
            comment: admin
            uid: 1050
            shell: /bin/bash
            password: "$6$q1kuowxeVHhyfU5N$3vuySF55BN7C1YnrK3fB7JrH.IHRv33jM.LgJ8m1ZToEPkgIa38ztlyTT4Qe3xOGlXYbXJ4B4OiCOa4.lYG8/."
            groups: sudo
            append: yes

        - name: Copy lighdm configuration file
          tags: lightdm
          copy:
            src: ./config/lightdm/lightdm.conf
            dest: /etc/lightdm/lightdm.conf
            owner: root
            group: root
            backup: yes

    - name: SSH CONFIGURATION
      tags: ssh
      block:
        - name: Copy SSH authorized keys for administrator user
          tags: authorized_keys
          copy:
            src: ./config/ssh/authorized_keys
            dest: /home/admin/.ssh/
            owner: admin
            group: admin
            mode: 0644

    - name: FIREWALL CONFIGURATION
      tags: firewall,ufw
      block:
        - name: Install ufw firewall
          apt: name=ufw state=present

        - name: Enable and start firewall service
          service: name=ufw state=started enabled=yes

        - name: Enable firewall and deny incoming requests
          ufw: state=enabled policy=deny logging=on

        - name: Allow OpenSSH service through firewall
          ufw: rule=allow name=OpenSSH

    - name: NETWORKING TOOLS INSTALLATION
      tags: networking
      block:
        - name: Copy packettracer.deb file
          tags: packettracer
          copy:
            src: ./packages/packettracer.deb
            dest: /home/admin/
            owner: admin
            group: admin
            mode: 0664

        - name: Install packettracer.deb
          tags: packettracer
          apt: deb=/home/admin/packettracer.deb
          ignore_errors: yes

        - name: Install WireShark
          tags: wireshark
          apt: name=wireshark state=present

        - name: Add wireshark group
          tags: wireshark
          group: name=wireshark state=present

        - name: Add guest user to wireshark group
          tags: wireshark
          user:
            name: guest
            groups: wireshark
            append: yes

        - name: Wireshark setuid
          ansible.builtin.debconf:
            name: wireshark-common
            question: wireshark-common/install-setuid
            value: yes
            vtype: boolean
          register: reconfigure_changed

        - name: Make debconf changes active for Wireshark
          ansible.builtin.command:
            cmd: "dpkg-reconfigure wireshark-common"
          environment:
            DEBIAN_FRONTEND: noninteractive
          when: reconfigure_changed.changed

    - name: JAVA DEVELOPEMENT TOOLS INSTALLATION
      tags: java
      block:
        - name: Install OpenJDK 17
          apt:
            name:
              - openjdk-17-jdk
              - openjdk-17-jre
              - openjdk-17-doc
              - openjdk-17-demo
              - openjdk-17-dbg
            state: present

        - name: Copy eclipse.tar.gz file
          tags: eclipse
          copy:
            src: ./packages/eclipse.tar.gz
            dest: /home/admin/
            owner: admin
            group: admin
            mode: 0664

        - name: Unarchive eclipse.tar.gz file into /opt
          tags: eclipse
          unarchive:
            src: /home/admin/eclipse.tar.gz
            dest: /opt
            remote_src: yes

        - name: Copy eclipse.desktop application launcher
          tags: eclipse
          copy:
            src: ./config/eclipse/eclipse.desktop
            dest: /usr/share/applications
            owner: root
            group: root
            mode: 0776

    - name: Install C developement tools
      tags: c
      apt:
        name:
          - make
          - build-essential
          - codeblocks
        state: present

    - name: Install Microsoft Visual Studio Code
      tags: vscode
      block:
        - name: Copy vscode.deb file
          copy:
            src: ./packages/vscode.deb
            dest: /home/admin/
            owner: admin
            group: admin
            mode: 0664

        - name: Install vscode.deb
          apt: deb=/home/admin/vscode.deb
  
    - name: CRON JOBS
      tags: crons
      block:
        - name: Add cron job for purging guest home directory
          tags: cron_purge_home
          cron:
            name: "a job for purging guest home folder on reboot"
            special_time: reboot
            job: "rm -rf /home/guest/*"
            state: present

    - name: Install extra utilities
      apt:
        name:
          - htop
          - neofetch
          - tree
          - vim
          - git
          - gitg
          - vlc
          - chromium
          - gimp
          - inkscape
          - mypaint
          - filezilla
        state: present

