---
- hosts: lab5
  user: debian
  become: yes

  roles:
    - { role: hostname, tags: hostname }
    - { role: time, tags: time }
    - { role: gantsign.keyboard, keyboard_model: pc105, keyboard_layout: fr }
#    - { role: upgrade, tags: upgrade }
    - { role: bash, tags: bash }
    - { role: guest, tags: guest }
    - { role: admin, tags: admin }
    - { role: desktop, tags: desktop }
    - { role: conky, tags: conky }
    - { role: firewall_host, tags: firewall }
    - { role: networking_lab, tags: networking }
    - { role: java_lab, tags: java }
    - { role: c_lab, tags: c }
    - { role: web_lab, tags: web }
    - { role: grub, tags: grub }
    - { role: zabbix_agent, tags: zabbix }
    - { role: extra, tags: extra }
