---
- hosts: all
  user: vagrant
  become: yes

  tasks:
    - name: Add admin and guest users
      tags: users
      block:
        - name: Add guest user
          user:
            name: guest
            comment: Guest
            uid: 1040
            shell: /bin/bash
            password: "$6$f.3g1cc1i/7KZNfc$T0.svXQuiNVwEA91XzINK1MjVtOy80/aJTCcgPNoSVqTDxZGm1559uGS5i.H1xPPcrU4KldAbQjXyseqtMqsx1"

    - name: Install and configure firewall
      tags: firewall,ufw
      block:
        - name: Install ufw firewall
          apt: name=ufw state=present

        - name: Enable firewall and deny incoming connections
          ufw:
            state: "enabled"
            policy: "deny"
            logging: "on"

        - name: Allow OpenSSH service
          ufw:
            rule: allow
            name: OpenSSH

    - name: Install C developement tools
      block:
        - name: Install build-essential and make
          apt:
            name:
              - build-essential
              - make
            state: present

        - name: Install Codeblocks
          apt: name=codeblocks state=present

    - name: Install Java developement tools
      block:
        - name: Install openJDK
          apt:
            name:
              - openjdk-17-jdk
              - openjdk-17-jre
              - openjdk-17-doc
              - openjdk-17-demo
              - openjdk-17-dbg
            state: present

