---
- hosts: all
  user: vagrant
  become: yes

  tasks:
    - name: Update cache and full system upgrade
      tags: update,upgrade,cache_update
      apt:
        update_cache: yes
        upgrade: dist
        cache_valid_time: 3600
        force_apt_get: yes

    - name: Add admin and guest users
      block:
        - name: Add guest user
          tags: users,guest
          user:
            name: guest
            comment: Guest
            uid: 1040
            shell: /bin/bash
            password: "$6$f.3g1cc1i/7KZNfc$T0.svXQuiNVwEA91XzINK1MjVtOy80/aJTCcgPNoSVqTDxZGm1559uGS5i.H1xPPcrU4KldAbQjXyseqtMqsx1"

        - name: Add admin user
          tags: users,admin
          user:
            name: admin
            comment: Admin
            uid: 1050
            shell: /bin/bash
            password: "$6$nMjUO4IaJ/KoYJdT$WYuIMkef8P0sTtI50drWP3JYuCWNCPlbZcWjCYKOU3xpKIY7m2J8vQQGn10WYPwCRQdmRXhv5YEe39J19do001"
            groups: sudo
            append: yes
    
    - name: Setup SSH server and keys
      block:
          # TODO: check if file exists before copy
        - name: Copy authorized keys to admin ssh directory
          tags: ssh,openssh,authorized_keys
          copy:
            src: ./ssh/authorized_keys
            dest: /home/admin/.ssh/
            owner: admin
            group: admin
            mode: "0644"

    - name: Install and configure firewall
      tags: firewall,ufw
      block:
        - name: Install ufw firewall
          apt: name=ufw state=present

        - name: Enable firewall and deny incoming connections
          ufw:
            state: "enabled"
            policy: "deny"
            logging: "on"

        - name: Allow OpenSSH service
          ufw:
            rule: allow
            name: OpenSSH

    - name: Install and configure MariaDB
      block:
        - name: Install MariaDB
          tags: database,mariadb
          apt:
            name:
              - mariadb-server
              - mariadb-client
            state: present

        - name: Enable and start MariaDB service
          tags: database,mariadb
          service:
            name: mariadb
            state: started
            enabled: yes

    - name: Install C developement tools
      block:
        - name: Install build-essential and make
          apt:
            name:
              - build-essential
              - make
            state: present

        - name: Install Codeblocks
          apt: name=codeblocks state=present

    - name: Install Java developement tools
      block:
        - name: Install openJDK
          apt:
            name:
              - openjdk-17-jdk
              - openjdk-17-jre
              - openjdk-17-doc
              - openjdk-17-demo
              - openjdk-17-dbg
            state: present

