- hosts: all
  user: vagrant
  become: yes

  tasks:
    - name: Install C developement tools
      block:
        - name: Install build-essential and make
          apt:
            name:
              - build-essential
              - make
            state: present

        - name: Install Codeblocks
          apt: name=codeblocks state=present

    - name: Install Java developement tools
      block:
        - name: Install openJDK
          apt:
            name:
              - openjdk-17-jdk
              - openjdk-17-jre
              - openjdk-17-doc
              - openjdk-17-demo
              - openjdk-17-dbg
            state: present

