---
- hosts: all
  user: vagrant
  become: yes

  tasks:
    - name: Update cache and full system upgrade
      tags: update,upgrade,cache_update
      apt:
        update_cache: yes
        upgrade: dist
        cache_valid_time: 3600
        force_apt_get: yes

    - name: Install and configure desktop environment
      tags: desktop
      block:
        - name: Install xfce4 and lightdm
          tags: xfce,xfce4
          apt:
            name:
              - xfce4
              - xfce4-goodies
              - lightdm

        - name: Enable lightdm service
          tags: lightdm
          service:
            name: lightdm
            state: started
            enabled: yes

    - name: Install Microsoft Visual Studio Code
      tags: code,vscode
      apt:
        deb: "https://az764295.vo.msecnd.net/stable/da76f93349a72022ca4670c1b84860304616aaa2/code_1.70.0-1659589288_amd64.deb"

    - name: Install command line tools
      tags: command_line
      apt:
        name:
          - htop
          - neofetch
          - tree
          - vim

    - name: Add admin and guest users
      block:
        - name: Add guest user
          tags: users,guest
          user:
            name: guest
            comment: Guest
            uid: 1040
            shell: /bin/bash
            password: "$6$f.3g1cc1i/7KZNfc$T0.svXQuiNVwEA91XzINK1MjVtOy80/aJTCcgPNoSVqTDxZGm1559uGS5i.H1xPPcrU4KldAbQjXyseqtMqsx1"

        - name: Add admin user
          tags: users,admin
          user:
            name: admin
            comment: Admin
            uid: 1050
            shell: /bin/bash
            password: "$6$nMjUO4IaJ/KoYJdT$WYuIMkef8P0sTtI50drWP3JYuCWNCPlbZcWjCYKOU3xpKIY7m2J8vQQGn10WYPwCRQdmRXhv5YEe39J19do001"
            groups: sudo
            append: yes
    
    - name: Setup SSH server and keys
      block:
          # TODO: check if file exists before copy
        - name: Copy authorized keys to admin ssh directory
          tags: ssh,openssh,authorized_keys
          copy:
            src: ./ssh/authorized_keys
            dest: /home/admin/.ssh/
            owner: admin
            group: admin
            mode: "0644"

    - name: Install and configure firewall
      tags: firewall,ufw
      block:
        - name: Install ufw firewall
          apt: name=ufw state=present

        - name: Enable firewall and deny incoming connections
          ufw:
            state: "enabled"
            policy: "deny"
            logging: "on"

        - name: Allow OpenSSH service
          ufw:
            rule: allow
            name: OpenSSH

    - name: Install and configure MariaDB
      tags: database,mariadb
      block:
        - name: Install MariaDB
          tags: database,mariadb
          apt:
            name:
              - mariadb-server
              - mariadb-client
            state: present

        - name: Enable and start MariaDB service
          tags: database,mariadb
          service:
            name: mariadb
            state: started
            enabled: yes

        - name: Install PyMySQL library
          tags: database,mariadb
          apt: name=python3-pymysql state=present

        - name: Create guest database
          tags: database,mariadb
          community.mysql.mysql_db:
            login_host: localhost
            login_user: root
            login_password: root
            name: guest_db
            state: present

        - name: Create guest user
          community.mysql.mysql_user:
            login_host: localhost
            login_user: root
            login_password: root
            name: guest
            state: present
            password: guest
            priv:
              'guest_db.*': 'ALL,GRANT'

    - name: Install SQLite and SQLite browser
      tags: database,sqlite
      apt:
        name:
          - sqlite3
          - sqlite3-doc
          - sqlitebrowser

    - name: Install C developement tools
      block:
        - name: Install build-essential and make
          apt:
            name:
              - build-essential
              - make
            state: present

        - name: Install Codeblocks
          apt: name=codeblocks state=present

    - name: Install Java developement tools
      block:
        - name: Install openJDK
          apt:
            name:
              - openjdk-17-jdk
              - openjdk-17-jre
              - openjdk-17-doc
              - openjdk-17-demo
              - openjdk-17-dbg
            state: present

