---
- hosts: servers
  user: vagrant
  become: yes

  tasks:
    - name: Update cache and full system upgrade
      tags: update,upgrade,cache_update
      dnf:
        name: '*'
        state: latest
        update_cache: yes

    - name: Install administation utilities
      tags: admin_utils,utils
      dnf:
        name: 
          - vim
          - tmux

    - name: Configure DNS service
      tags: dns
      block:
        - name: Install DNS and DNS utilities
          dnf:
            name:
              - bind
              - bind-utils
            state: present

        - name: Copy named config file
          tags: named,named_config
          copy:
            src: config/bind/named.conf
            dest: /etc/named.conf
            owner: root
            group: root
            mode: 0640
            backup: yes

