---
- hosts: servers
  user: ouail
  become: yes

  pre_tasks:
    - name: Update cache and full system upgrade
      tags: update,upgrade
      apt:
        update_cache: yes
        upgrade: dist
        cache_valid_time: 3600
        force_apt_get: yes

    - name: Install administration utilities
      tags: admin_utilities
      apt:
        name:
          - vim
          - htop
          - neofetch
          - fzf
          - tree
          - tmux

  tasks:
    - name: Configure DNS service
      tags: dns
      block:
        - name: Install DNS and DNS utilities
          tags: dns_install
          apt:
            name:
              - bind9
              - bind9-doc
              - bind9-utils
              - bind9-dnsutils
            state: present

        - name: Copy named configuration file
          tags: named,named_config
          copy:
            src: config/bind/named.conf
            dest: /etc/named.conf
            owner: root
            group: named
            mode: 0640
            backup: yes

        - name: Copy zones configuration file
          tags: named,zones_config
          copy:
            src: config/bind/named.conf.local
            dest: /etc/named/named.conf.local
            owner: root
            group: named
            mode: 0640

        - name: Copy zones database files
          tags: named,zones_db
          copy:
            src: config/bind/zones/
            dest: /etc/named/zones/
            owner: root
            group: named
            mode: 0640

        - name: Enable and run named service
          tags: named,named_service
          service:
            name: named
            state: started
            enabled: yes

