---
- hosts: servers
  user: ouail
  become: yes

  pre_tasks:
#    - name: Update cache and full system upgrade
#      tags: update,upgrade
#      apt:
#        update_cache: yes
#        upgrade: dist
#        cache_valid_time: 3600
#        force_apt_get: yes

    - name: Install administration utilities
      tags: admin_utilities
      apt:
        name:
          - vim
          - htop
          - neofetch
          - fzf
          - tree
          - tmux
