---
- hosts: servers
  user: vagrant
  become: yes

  tasks:
    - name: Update cache and full system upgrade
      tags: update,upgrade,cache_update
      dnf:
        name: '*'
        state: latest
        update_cache: yes

    - name: Configure DNS service
      tags: dns
      block:
        - name: Install DNS and DNS utilities
          dnf:
            name:
              - bind
              - bind-utils
            state: present
