---
- hosts: servers
  user: ouail
  become: yes

  pre_tasks:
    - name: Update cache and full system upgrade
      tags: update,upgrade
      apt:
        update_cache: yes
        upgrade: dist
        cache_valid_time: 3600
        force_apt_get: yes

    - name: Install administration utilities
      tags: admin_utilities
      apt:
        name:
          - vim
          - htop
          - neofetch
          - fzf
          - tree
          - tmux

  tasks:
    - name: Configure DNS service
      tags: dns
      block:
        - name: Install DNS and DNS utilities
          tags: dns_install
          apt:
            name:
              - bind9
              - bind9-doc
              - bind9-utils
              - bind9-dnsutils
            state: present

        - name: Copy named configuration file
          tags: named,named_config
          copy:
            src: config/bind/named.conf
            dest: /etc/bind/named.conf
            owner: root
            group: root
            mode: 0644
            backup: yes

        - name: Copy zones configuration file
          tags: named,zones_config
          copy:
            src: config/bind/named.conf.local
            dest: /etc/bind/named.conf.local
            owner: root
            group: root
            mode: 0644

        - name: Copy zones database files
          tags: named,zones_db
          copy:
            src: config/bind/zones/
            dest: /etc/bind/zones/
            owner: root
            group: root
            mode: 0644

        - name: Enable and run named service
          tags: named,named_service
          service:
            name: named
            state: started
            enabled: yes

    - name: SAMBA CONFIGURATION
      tags: samba
      block:
        - name: Install samba
          apt: name=samba state=present

        - name: Enable and run samba service
          service:
            name: "{{ item }}"
            state: started
            enabled: yes
          with_items:
            - smbd
            - nmbd

        - name: Create `teachers` group
          group: name=teachers state=present

        - name: Create teacher samba user
          user:
            name: teacher
            comment: teacher
            shell: /sbin/nologin
            create_home: no
            groups: teachers
            append: yes
            state: present

        - name: Create samba folders hierarchy
          block:
            - name: Create root samba shares directory
              file:
                path: /home/samba/
                state: directory
                owner: root
                group: root

            - name: Create SHARED and ASSIGNMENTS directories
              file:
                path: /home/samba/{{ item }}
                state: directory
                owner: root
                group: root
              with_items:
                - Shared
                - Assignments

            - name: Create SHARED directories for ENGINEERING and LMD classes
              file:
                path: /home/samba/Shared/{{ item }}
                state: directory
                owner: root
                group: teachers
                mode: 0755
              with_items:
                - ENG
                - LMD

            - name: Create semesters directories for LMD class
              file:
                path: /home/samba/Shared/LMD/{{ item }}
                state: directory
                owner: root
                group: teachers
                mode: 0755
              with_items:
                - S1
                - S2
                - S3
                - S4

            - name: Create modules directories for each semester
              file:
                path: /home/samba/Shared/LMD/{{ item.semester }}/{{ item.subject }}
                state: directory
                owner: root
                group: teachers
                mode: 0775
              with_items:
                - { semester: S1, subject: ALGO1 }
                - { semester: S2, subject: IPO }
                - { semester: S2, subject: PSD }
                - { semester: S3, subject: POO }
                - { semester: S3, subject: ASD }
                - { semester: S3, subject: AO }
                - { semester: S4, subject: SE1 }
                - { semester: S4, subject: BD }
                - { semester: S4, subject: RES }
                - { semester: S4, subject: DAO }

        - name: Copy samba server configuration file
          template:
            src: ./templates/smb.conf.j2
            dest: /etc/samba/smb.conf
            owner: root
            group: root
            mode: '0644'
          vars:
            network: 10.0.0.0
            mask: 16
            interface: eth0

        - name: Restart samba service
          service:
            name: "{{ item }}"
            state: restarted
          with_items:
            - smbd
            - nmbd