---
- hosts: servers
  user: vagrant
  become: yes

  tasks:
    - name: Update cache and full system upgrade
      tags: update,upgrade,cache_update
      dnf:
        name: '*'
        state: latest
        update_cache: yes
