---
- name: install packages
  apt:
    name:
      - htop
      - neofetch
      - tree
      - vim
      - git
      - gitg
      - vlc
      - chromium
      - gimp
      - inkscape
      - mypaint
      - filezilla
      - numlockx
      - dosbox
      - zip
      - unzip
    state: present

- name: copy packet tracer deb file
  copy:
    src: qtspim.deb
    dest: /opt
    owner: root
    group: root

- name: install packet tracer
  apt: deb=/opt/qtspim.deb
