# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.define "lab_machine_1" do |lab_machine|
    lab_machine.vm.box = "debian/bullseye64"
    lab_machine.vm.hostname = "machine1.lab1.local"
    lab_machine.vm.network "public_network"

    lab_machine.vm.provider "virtualbox" do |vb|
      vb.gui = true
      vb.memory = "1024"
    end
  end

  config.vm.define "server_1" do |server|
    server.vm.box = "centos/7"
    server.vm.hostname = "server1.local"
    server.vm.network "public_network"

    server.vm.provider "virtualbox" do |vb|
      vb.gui = false
      vb.memory = "512"
    end
  end

end

