---
- name: install mariadb server and client
  apt:
    name:
      - mariadb-server
      - mariadb-client
    state: present

- name: enable and run mariadb service
  service:
    name: mariadb
    state: started
    enabled: yes

- name: install pymysql
  apt: name=python3-pymysql state=present

- name: create guest database
  community.mysql.mysql_db:
    name: guest_db
    state: present
    login_user: root
    login_password: root

- name:
  community.mysql.mysql_user:
    name: guest
    password: guest
    state: present
    priv:
      'guest_db.*': 'ALL,GRANT'
    login_user: root
    login_password: root

- name: copy purge database service
  copy:
    src: purge-guest-database.service
    dest: /etc/systemd/system/
    owner: root
    group: root
    mode: 0744

- name: enable and run purge database service
  service:
    state: started
    enabled: yes
    daemon_reload: yes
    name: purge-guest-database.service
