---
- name: install php 7 and required modules
  apt:
    name:
      - php
      - php-zip
      - php-yaml
      - php-mysql
      - php-ldap
      - php-bcmath
      - php-mbstring
      - php-gd
      - php-pdo
      - php-xml
      - php-sqlite3
      - libapache2-mod-php
    state: present

- name: install apacher server
  apt: name=apache2 state=present

- name: enable and run apache service
  service:
    name: apache2
    state: started
    enabled: yes

- name: copy vscode deb file
  copy:
    src: vscode.deb
    dest: /opt
    owner: admin
    group: admin

- name: install vscode
  apt: deb=/opt/vscode.deb
  ignore_errors: yes
